---
- name: Install Go package
  ansible.builtin.package:
    name: golang
    state: present
  become: true

- name: Add golang plugin to Oh My Zsh
  ansible.builtin.set_fact:
    oh_my_zsh_plugins: "{{ oh_my_zsh_plugins + ['golang'] }}"
