---
- name: Install required system packages
  ansible.builtin.package:
    name:
      - git
      - curl
    state: present
  become: true

- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: true

- name: Install Oh My Zsh
  ansible.builtin.shell: |
    set -o pipefail
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh/"

- name: Install Powerlevel10k theme
  block:
    - name: Clone Powerlevel10k repository
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1
        version: master

    - name: Deploy Powerlevel10k configuration file
      ansible.builtin.copy:
        src: .p10k.zsh
        dest: "{{ ansible_env.HOME }}/"
        mode: '0644'

- name: Install Zsh plugins
  block:
    - name: Clone zsh-autosuggestions plugin repository
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        version: master


    - name: Clone zsh-syntax-highlighting plugin repository
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        version: master

    - name: Add cloned plugins to Oh My Zsh
      ansible.builtin.set_fact:
        oh_my_zsh_plugins: "{{ oh_my_zsh_plugins + ['zsh-autosuggestions', 'zsh-syntax-highlighting'] }}"


- name: Generate Zsh configuration
  block:
    - name: Add dnf plugin to Oh My Zsh (RedHat)
      ansible.builtin.set_fact:
        oh_my_zsh_plugins: "{{ oh_my_zsh_plugins + ['dnf'] }}"
      when: ansible_os_family == "RedHat"

    - name: Create .zshrc from template
      ansible.builtin.template:
        src: .zshrc.j2
        dest: "{{ ansible_env.HOME }}/.zshrc"
        mode: '0644'
      vars:
        plugins: "{{ oh_my_zsh_plugins }}"

- name: Set default shell to /bin/zsh for current user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true
