- name: Install bpython uv tool
  ansible.builtin.command:
    cmd: uv tool install bpython
  register: tmp
  changed_when: tmp.stdout != "`bpython` is already installed:"

- name: Add uv plugin to Oh My Zsh
  ansible.builtin.set_fact:
    oh_my_zsh_plugins: "{{ oh_my_zsh_plugins + ['uv'] }}"
