- name: Install bpython uv tool
  ansible.builtin.command:
    cmd: uv tool install bpython
  register: tmp
  changed_when: '"is already installed" not in tmp.stderr'

- name: Add uv plugin to Oh My Zsh
  ansible.builtin.set_fact:
    oh_my_zsh_plugins: "{{ oh_my_zsh_plugins + ['uv'] }}"
