---
- name: Enable Ghostty COPR repository (RedHat)
  community.general.copr:
    name: pgdev/ghostty
    state: enabled
  become: true
  when: ansible_os_family == "RedHat"

- name: Install Ghostty package
  ansible.builtin.package:
    name: ghostty
    state: present
  become: true

- name: Deploy Ghostty configuration file
  ansible.builtin.copy:
    src: config
    dest: "~/.config/ghostty/"
    mode: '0644'
