---
- name: Add Ghostty repository (RedHat)
  community.general.copr:
    name: pgdev/ghostty
    state: enabled
  when: ansible_os_family == "RedHat"

- name: Install Ghostty (RedHat)
  ansible.builtin.dnf:
    name: ghostty
    state: present
  when: ansible_os_family == "RedHat"
