---
- name: Install Docker
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://get.docker.com | sh
  args:
    creates: "/usr/bin/docker"
  become: true

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    group: docker
  become: true
